version: '3.8'
services:
  postgresdb-resource:
    container_name: postgresdb-resource
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SERVICE_PORT=${DB_SERVICE_PORT}
    ports:
      - "${DB_SERVICE_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  resource-service-compose:
    container_name: resource-service-compose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RESOURCE_SERVICE_PORT_EXPOSED}:${RESOURCE_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_SERVICE_HOST}:${DB_SERVICE_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - RESOURCE_SERVICE_PORT=${RESOURCE_SERVICE_PORT}
      - RESOURCE_SERVICE_PORT_EXPOSED=${RESOURCE_SERVICE_PORT_EXPOSED}
      - SONG_SERVICE_HOST=${SONG_SERVICE_HOST}
    depends_on:
      - postgresdb-resource

