version: '3.8'
services:
  resource-service-comp:
    container_name: resource-service-comp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RESOURCE_SERVICE_PORT_EXPOSED}:${RESOURCE_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_SERVICE_HOST}:${DB_SERVICE_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - RESOURCE_SERVICE_PORT=${RESOURCE_SERVICE_PORT}
      - RESOURCE_SERVICE_PORT_EXPOSED=${RESOURCE_SERVICE_PORT_EXPOSED}
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SERVICE_PORT=${DB_SERVICE_PORT}
    ports:
      - "${DB_SERVICE_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
