server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/music_resource
#    url: jdbc:postgresql://localhost:5432/music_resource
    url: jdbc:postgresql://${DB_SERVICE_NAME}:${DB_SERVICE_PORT}/${DB_NAME}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  hibernate:
    ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

song:
  service:
    endpoint: /api/v1/songs
    url: ${SONG_SERVICE_HOST}
