server:
  port: ${RESOURCE_SERVICE_PORT}

spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/music_resource
#    url: jdbc:postgresql://localhost:5432/music_resource
    url: jdbc:postgresql://${DB_SERVICE_HOST}:${DB_SERVICE_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  hibernate:
    ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud.stream.bindings:
    output.destination:message_queue
    input.destination:message_queue

aws:
  region: "us-east-1"
  bucketName: "bucketName"